[workspace]
resolver = "3"

members = [
    "01_hello-world",
    "02_guessing_game",
    "03_common_programming_concepts/*",
    "04_ownership/*",
    "05_structs/*",
    "06_enums_and_pattern-matching/*",
    "07_packages_crates_and_modules/*",
    "08_common_collections/*",
    "09_error_handling/*",
    "10_generic_traits_and_lifetimes/*", 
    "11_writing_automated_tests/*",
]

exclude = [
    "rustlings"
]
