fn main() {
    // TODO: Create an array called `a` with at least 100 elements in it.
    // let a = ???

    let a = [
        "Messi",
        "Ronaldo",
        "Pelé",
        "Maradona",
        "Puskás",
        "Gerd Müller",
        "Franz Beckenbauer",
        "Johan Cruyff",
        "Diego Maradona",
        "Pelé",
        "Bobby Fischer",
        "José Martínez",
        "Eusébio",
        "Garrincha",
        "Charlie George",
        "George Best",
        "Bobby Charlton",
        "Alfredo Di Stéfano",
        "Gianni Rivera",
        "Lev Yashin",
        "Giacinto Facchetti",
        "Bobby Moore",
        "Uwe Seeler",
        "Gianluigi Buffon",
        "Zinedine Zidane",
        "Luka Modrić",
        "Cristiano Ronaldo",
        "Lionel Messi",
        "Pelé",
        "Zinedine Zidane",
        "Luka Modrić",
        "Cristiano Ronaldo",
        "Neymar Jr",
        "Kylian Mbappé",
        "Mohamed Salah",
        "Sergio Ramos",
        "Andrés Iniesta",
        "Xavi Hernández",
        "Steven Gerrard",
        "John Terry",
        "Javier Mascherano",
        "Sergio Busquets",
        "Eden Hazard",
        "Arjen Robben",
        "Franck Ribéry",
        "Gareth Bale",
        "Robert Lewandowski",
        "Sergio Agüero",
        "Carlos Tévez",
        "Thierry Henry",
        "Didier Drogba",
        "Samuel Eto'o",
        "Karim Benzema",
        "Gonzalo Higuaín",
        "Mario Balotelli",
        "Romário",
        "Ronaldo",
        "Ronaldinho",
        "Ronaldinho Gaúcho",
        "Marta",
        "Abby Wambach",
        "Mia Hamm",
        "Alex Morgan",
        "Hope Solo",
        "Megan Rapinoe",
        "Tobin Heath",
        "Carli Lloyd",
        "Meghan Klingenberg",
        "Crystal Dunn",
        "Ali Krieger",
        "Kelley O'Hara",
        "Becky Sauerbrunn",
        "Pia Sundhage",
        "Jill Ellis",
        "Gregg Berhalter",
        "Gina Lewandowski",
        "Christine Sinclair",
        "Abby Dahlkemper",
        "Sam Mewis",
        "Rose Lavelle",
        "Sophia Smith",
        "Gio Reyna",
        "Weston McKennie",
        "Tyler Adams",
        "Sergiño Dest",
        "Zack Steffen",
        "Clint Dempsey",
        "Landon Donovan",
        "DaMarcus Beasley",
        "Kyle Beckerman",
        "Michael Bradley",
        "Jürgen Klinsmann",
        "Antonio di Natale",
        "Petr Čech",
        "Gianluigi Buffon",
        "René Adler",
        "Iker Casillas",
        "Víctor Valdés",
        "Ederson",
        "Manuel Neuer",
        "Alisson",
        "Jan Oblak",
        "David de Gea",
    ];

    if a.len() >= 100 {
        println!("Wow, that's a big array!");
    } else {
        println!("Meh, I eat arrays like that for breakfast.");
        panic!("Array not big enough, more elements needed");
    }
}
